#' Define the imported variables to be used for downstream analysis.
#' @param data The data frame to define variables from.
#' @param input_date Optional. Input column containing in the data frame ###
#' @param input_temp Optional. Input column containing temperature in the data frame
#' @param input_rhum Optional. Input column containing relative humidity in the data frame
#' @param input_wood Optional. Input column containing wood moisture in the data frame
#' @param input_ohm Optional. Input column containing ohm in the data frame
#' @return A data frame with added columns defined for downstream analysis.
#' @import dplyr
#' @import tidyr
#' @export
#' @examples
#' \dontrun{
#' describe(dataset)
#' describe(dataset, col1, col2)
#' }
#'
#'
# -- Site ID SHOULD BE GENERATED BY THE DATA IMPORT
# -- Sensor ID FROM SENSOR ID AND PORT IF MULTIPLE
# -- date
# -- temp
# -- rh
# -- wood rh
# -- ohm
#'
define_variables <- function(data,
                             input_date, ## Denne må sjekkes for datetime varianter
                             input_temp,
                             input_rhum,
                             input_wood,
                             input_ohm,
                             output_date = gen_date,
                             output_temp = gen_temp,
                             output_rhum = gen_rhum,
                             output_wood = gen_wood,
                             output_ohm = gen_ohm
                             # site_ID = NULL,
                             # sensor_ID = NULL,
                             # timeframe = c("hour", "day", "week", "month")
) {
  if (!missing(input_date)) {
    data %>%
      dplyr::mutate(
        {{ output_date }} := lubridate::ymd_hms({{ input_date }})
      )
  } # else {
  # data %>%
  #   dplyr::mutate(
  #     {{output_date}} := NULL)
  # }
  if (!missing(input_temp)) {
    x <- data %>%
      dplyr::mutate(
        {{ output_temp }} := ({{ input_temp }})
      )
  } else {
    stop("No temperature column to defined is specified")
  }
  # if(!is.null(input_rhum)) {
  #   data %>%
  #     dplyr::mutate(
  #       {{output_rhum}} := as.double({{input_rhum}})
  #     )
  # }
  if (!missing(input_wood)) {
    x <- data %>%
      dplyr::mutate(
        {{ output_wood }} := .parse_numeric({{ input_wood }})
      )
  }
  # if(!is.null(input_ohm)) {
  #   data %>%
  #     dplyr::mutate(
  #       {{output_ohm}} := as.double({{input_ohm}})
  #     )
}

#####
## Date
#####
#' Normalize date/time from unified or split columns
#'
#' @description
#' `define_variables_datetime()` creates standardized datetime, date, and time variables
#' from either a single unified datetime column (`input_datetime`) or a pair of
#' columns (`input_date` + `input_time`). It accepts bare names or strings for
#' the input columns. When only a date is provided, time defaults to `00:00:00`.
#'
#' @param data A data frame.
#' @param input_datetime Bare name or string. Unified datetime column. Optional if `input_date` and `input_time` are provided.
#' @param input_date Bare name or string. Date column. Optional if `input_datetime` is provided.
#' @param input_time Bare name or string. Time column (e.g., "14:30", "14:30:05"). Optional; if missing, defaults to "00:00:00".
#' @param tz Character. Target time zone for the parsed datetime (default "UTC").
#' @param output_datetime Name of the output datetime column (default "gen_datetime").
#' @param output_date Name of the output date column (default "gen_date").
#' @param output_time Name of the output time column (default "gen_time").
#' @param quiet Logical. If `TRUE`, suppresses informative messages.
#'
#' @return The input data frame with added/overwritten `output_datetime`, `output_date`, and `output_time`.
#'
#' @examples
#' # 1) Unified datetime:
#' # data %>% define_variables_datetime(input_datetime = dt, tz = "Europe/Oslo")
#'
#' # 2) Split date + time:
#' # data %>% define_variables_datetime(input_date = dato, input_time = klokke)
#'
#' # 3) Only date (time defaults to midnight):
#' # data %>% define_variables_datetime(input_date = sample_date)
#'
#' @import dplyr
#' @importFrom rlang ensym as_string :=
#' @importFrom parsedate parse_date
#' @importFrom lubridate as_date hms is.POSIXt force_tz
#' @export
define_variables_datetime <- function(
    data,
    input_datetime = NULL,
    input_date = NULL,
    input_time = NULL,
    tz = "UTC",
    output_datetime = "gen_datetime",
    output_date = "gen_date",
    output_time = "gen_time",
    quiet = FALSE
) {
  # helpers to get column names (or NULL)
  get_col <- function(x) {
    if (is.null(x)) return(NULL)
    rlang::as_string(rlang::ensym(x))
  }

  dt_col   <- get_col(input_datetime)
  date_col <- get_col(input_date)
  time_col <- get_col(input_time)

  if (is.null(dt_col) && is.null(date_col)) {
    stop("Provide either `input_datetime` or `input_date` (with optional `input_time`).", call. = FALSE)
  }
  if (!is.null(dt_col) && (!is.null(date_col) || !is.null(time_col)) && !quiet) {
    message("Both unified datetime and date/time provided. Using `input_datetime` and ignoring split inputs.")
  }

  out_dt   <- output_datetime
  out_date <- output_date
  out_time <- output_time

  out <- dplyr::mutate(data,
                       # 1) Build a normalized POSIXct (out_dt)
                       !!out_dt := {
                         if (!is.null(dt_col)) {
                           # Unified datetime path
                           x <- .data[[dt_col]]
                           # If character/factor -> parse; if already POSIX -> keep; if Date -> make midnight
                           if (inherits(x, "POSIXt")) {
                             lubridate::force_tz(x, tzone = tz)
                           } else if (inherits(x, "Date")) {
                             lubridate::force_tz(as.POSIXct(x), tzone = tz)
                           } else {
                             lubridate::parse_date_time(as.character(x), orders = c("YmdHMS", "Ymd HMS", "dmYHMS", "mdYHMS", "Ymd"), tz = tz, quiet = TRUE)
                           }
                         } else {
                           # Split date + time path
                           d <- .data[[date_col]]
                           # Parse date robustly
                           d_parsed <- if (inherits(d, "Date")) {
                             d
                           } else {
                             parsedate::parse_date(as.character(d))
                           }

                           # Time handling
                           if (is.null(time_col)) {
                             t_str <- rep("00:00:00", length(d_parsed))
                           } else {
                             t_raw <- .data[[time_col]]
                             # If it's hms, format; else assume character-ish and keep
                             if (inherits(t_raw, "hms")) {
                               t_str <- format(t_raw)
                             } else {
                               t_str <- ifelse(is.na(t_raw) | trimws(as.character(t_raw)) == "",
                                               "00:00:00",
                                               as.character(t_raw))
                             }
                           }

                           combo <- ifelse(is.na(d_parsed), NA_character_,
                                           paste0(as.character(d_parsed), " ", t_str))
                           lubridate::parse_date_time(combo, orders = c("YmdHMS", "Ymd HMS", "dmYHMS", "mdYHMS", "Ymd"), tz = tz, quiet = TRUE)
                         }
                       },
                       # 2) Derive date and time from the normalized POSIXct
                       !!out_date := lubridate::as_date(.data[[out_dt]]),
                       !!out_time := {
                         dtv <- .data[[out_dt]]
                         ifelse(is.na(dtv), NA_character_, format(dtv, "%H:%M:%S"))
                       }
  )

  out
}

# ------------------------------------------------------------------------------

#' Define Date Variable (wrapper)
#'
#' @description
#' Backward-compatible convenience wrapper that creates a normalized date
#' variable from a single input date column. Internally calls
#' `define_variables_datetime()` and returns the same three standardized outputs
#' (`gen_datetime`, `gen_date`, `gen_time`) unless you change the output names.
#'
#' @param data A data frame.
#' @param input_date Bare name or string. Date column to parse.
#' @param output_date Name of the new date variable to be created (default "gen_date").
#' @param tz Character. Target time zone for the parsed datetime (default "UTC").
#'
#' @return A modified data frame with `gen_date` (and also `gen_datetime`, `gen_time`).
#'
#' @examples
#' # data %>% define_variables_date(input_date = DateColumn)
#'
#' @import dplyr
#' @importFrom rlang ensym as_string
#' @export
define_variables_date <- function(data,
                                  input_date,
                                  output_date = "gen_date",
                                  tz = "UTC") {
  date_col <- rlang::as_string(rlang::ensym(input_date))

  define_variables_datetime(
    data = data,
    input_date = date_col,
    tz = tz,
    output_date = output_date
  )
}

#' #' Define Date Variable
#' #'
#' #' This function takes a data frame and defines a date variable based on the provided input
#' #' date column, using the specified date format.
#' #'
#' #' @param data The input data frame.
#' #' @param input_date The name or expression of the date column.
#' #' @param date_format The format of the input date column ("ymd" for Year-Month-Day or "dmy" for Day-Month-Year).
#' #' @param output_date The name of the new date variable to be created.
#' #'
#' #' @import dplyr
#' #' @importFrom lubridate ymd dmy
#' #'
#' #' @return A modified data frame with the new date variable added.
#' #'
#' #' @examples
#' #' # Example usage with "ymd" format:
#' #' data_with_date <- define_variables_date(
#' #'   data = my_data, input_date = DateColumn,
#' #'   date_format = "ymd", output_date = NewDate
#' #' )
#' #'
#' #' # Example usage with "dmy" format:
#' #' data_with_date <- define_variables_date(
#' #'   data = my_data, input_date = DateColumn,
#' #'   date_format = "dmy", output_date = NewDate
#' #' )
#' #'
#' #' @export
#' #'
#' define_variables_date <- function(data,
#'                                   input_date,
#'                                   output_date = "gen_date") {
#'   if (!missing(input_date) && !is.null(input_date)) {
#'     data %>%
#'       mutate(!!sym(output_date) := parsedate::parse_date(.data[[input_date]]))
#'   } else {
#'     stop("No date column to define is specified")
#'   }
#' }


#####
## Sensor ID
#####
#' Define Sensor ID Variable
#'
#' This function takes a data frame and defines a sensor ID variable based on the provided input
#' sensor and port columns. It can create a sensor ID by concatenating the sensor and port values
#' with an underscore or use the sensor column directly.
#'
#' @param data The input data frame.
#' @param input_sensor The name or expression of the sensor column.
#' @param input_port The name or expression of the port column (optional).
#' @param output_sensorID The name of the new sensor ID variable to be created.
#'
#' @import dplyr
#'
#' @return A modified data frame with the new sensor ID variable added.
#'
#' @examples
#' # Example usage with sensor and port columns:
#' data_with_sensorID <- define_variables_sensorID(
#'   data = my_data, input_sensor = Sensor,
#'   input_port = Port, output_sensorID = SensorID
#' )
#'
#' # Example usage with only a sensor column:
#' data_with_sensorID <- define_variables_sensorID(
#'   data = my_data, input_sensor = Sensor,
#'   output_sensorID = gen_SensorID
#' )
#'
#' @export
define_variables_sensorID <- function(data,
                                      input_sensor,
                                      input_port,
                                      output_sensorID = gen_sensorID) {
  if (!missing(input_sensor) & missing(input_port)) {
    data %>%
      dplyr::mutate(
        {{ output_sensorID }} := as.character({{ input_sensor }})
      )
  } else if (!missing(input_sensor) & !missing(input_port)) {
    data %>%
      dplyr::mutate(
        {{ output_sensorID }} := paste0({{ input_sensor }}, "_", {{ input_port }})
      )
  } else {
    stop("No sensor ID column to define is specified")
  }
}

# define_variables_sensorID <- function(data,
#                                       input_sensor,
#                                       input_port,
#                                       output_sensorID = gen_sensorID) {
#   if (!missing(input_sensor) & missing(input_port)) {
#     data %>%
#       dplyr::mutate(
#         {{ output_sensorID }} := as.character({{ input_sensor }})
#       )
#   } else if (!missing(input_sensor) & !missing(input_port)) {
#     data %>%
#       dplyr::mutate(
#         {{ output_sensorID }} := paste0({{ input_sensor }}, "_", {{ input_port }})
#       )
#   } else {
#     stop("No sensor ID column to define is specified")
#   }
# }

# Internal helper: parse numeric, handling both "." and "," as decimal separator.
# Works on character, factor, or already-numeric vectors.
.parse_numeric <- function(x) {
  if (is.numeric(x)) return(x)
  as.double(gsub(",", ".", as.character(x)))
}

#####
## Temperature
#####
#' Define Temperature Variable
#'
#' This function takes a data frame and defines a temperature variable based on the provided input
#' temperature column, converting it to a double type if necessary.
#'
#' @param data The input data frame.
#' @param input_temp The name or expression of the temperature column.
#' @param output_temp The name of the new temperature variable to be created.
#'
#' @import dplyr
#'
#' @return A modified data frame with the new temperature variable added.
#'
#' @examples
#' # Example usage:
#' data_with_temperature <- define_variables_temp(
#'   data = my_data, input_temp = Temperature,
#'   output_temp = gen_temp
#' )
#'
#' @export
define_variables_temp <- function(data,
                                  input_temp,
                                  output_temp = gen_temp) {
  if (!missing(input_temp)) {
    data %>%
      dplyr::mutate(
        {{ output_temp }} := .parse_numeric({{ input_temp }})
      )
  } else {
    stop("No temperature column to define is specified")
  }
}

# define_variables_temp <- function(data,
#                                   input_temp,
#                                   output_temp = gen_temp) {
#   if (!missing(input_temp)) {
#     data %>%
#       dplyr::mutate(
#         {{ output_temp }} := .parse_numeric({{ input_temp }})
#       )
#   } else {
#     stop("No temperature column to define is specified")
#   }
# }

#####
## Relative humidity
#####
#' Define Relative Humidity Variable
#'
#' This function takes a data frame and defines a relative humidity variable based on the provided input
#' relative humidity column, converting it to a double type if necessary.
#'
#' @param data The input data frame.
#' @param input_rhum The name or expression of the relative humidity column.
#' @param output_rhum The name of the new relative humidity variable to be created.
#'
#' @import dplyr
#'
#' @return A modified data frame with the new relative humidity variable added.
#'
#' @examples
#' # Example usage:
#' data_with_rhum <- define_variables_rhum(
#'   data = my_data, input_rhum = RelativeHumidity,
#'   output_rhum = gen_rhum
#' )
#'
#' @export
define_variables_rhum <- function(data,
                                  input_rhum,
                                  output_rhum = gen_rhum) {
  if (!missing(input_rhum)) {
    data %>%
      dplyr::mutate(
        {{ output_rhum }} := .parse_numeric({{ input_rhum }})
      )
  } else {
    stop("No relative humidity column to define is specified")
  }
}

# define_variables_rhum <- function(data,
#                                   input_rhum,
#                                   output_rhum = gen_rhum) {
#   if (!missing(input_rhum)) {
#     data %>%
#       dplyr::mutate(
#         {{ output_rhum }} := .parse_numeric({{ input_rhum }})
#       )
#   } else {
#     stop("No relative humidity column to define is specified")
#   }
# }

#####
## Wood moisture
#####
#' Define Wood Moisture Variable
#'
#' This function takes a data frame and defines a wood moisture variable based on the provided input
#' wood moisture column, converting it to a double type if necessary.
#'
#' @param data The input data frame.
#' @param input_wood The name or expression of the wood moisture column.
#' @param output_wood The name of the new wood moisture variable to be created.
#'
#' @import dplyr
#'
#' @return A modified data frame with the new wood moisture variable added.
#'
#' @examples
#' # Example usage:
#' data_with_wood <- define_variables_wood(
#'   data = my_data, input_wood = WoodMoisture,
#'   output_wood = gen_wood
#' )
#'
#' @export
define_variables_wood <- function(data,
                                  input_wood,
                                  output_wood = gen_wood) {
  if (!missing(input_wood)) {
    data %>%
      dplyr::mutate(
        {{ output_wood }} := .parse_numeric({{ input_wood }})
      )
  } else {
    stop("No wood moisture column to define is specified")
  }
}

# define_variables_wood <- function(data,
#                                   input_wood,
#                                   output_wood = gen_wood) {
#   if (!missing(input_wood)) {
#     data %>%
#       dplyr::mutate(
#         {{ output_wood }} := .parse_numeric({{ input_wood }})
#       )
#   } else {
#     stop("No wood moisture column to define is specified")
#   }
# }

#####
## Ohm raw value
#####
#' Define Ohm Value Variable
#'
#' This function takes a data frame and defines an Ohm value variable based on the provided input
#' Ohm value column, converting it to a double type if necessary.
#'
#' @param data The input data frame.
#' @param input_ohm The name or expression of the Ohm value column.
#' @param output_ohm The name of the new Ohm value variable to be created.
#'
#' @import dplyr
#'
#' @return A modified data frame with the new Ohm value variable added.
#'
#' @examples
#' # Example usage:
#' data_with_ohm <- define_variables_ohm(
#'   data = my_data, input_ohm = OhmValue,
#'   output_ohm = gen_ohm
#' )
#'
#' @export
define_variables_ohm <- function(data,
                                 input_ohm,
                                 output_ohm = gen_ohm) {
  if (!missing(input_ohm)) {
    data %>%
      dplyr::mutate(
        {{ output_ohm }} := .parse_numeric({{ input_ohm }})
      )
  } else {
    stop("No Ohm value column to define is specified")
  }
}

# define_variables_ohm <- function(data,
#                                  input_ohm,
#                                  output_ohm = gen_ohm) {
#   if (!missing(input_ohm)) {
#     data %>%
#       dplyr::mutate(
#         {{ output_ohm }} := .parse_numeric({{ input_ohm }})
#       )
#   } else {
#     stop("No Ohm value column to defined is specified")
#   }
# }
